"""descricao_da_mudanca

Revision ID: 0e8d342491eb
Revises: 0be7ebeeb1a7
Create Date: 2025-10-15 01:59:01.937042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8d342491eb'
down_revision: Union[str, None] = '0be7ebeeb1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
