"""add vehicles table

Revision ID: 1ab32111fd7c
Revises: c51b78780ba6
Create Date: 2025-09-30 03:21:49.293698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ab32111fd7c'
down_revision: Union[str, None] = 'c51b78780ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('store_id', sa.UUID(), nullable=False))
    op.add_column('vehicles', sa.Column('brand', sa.String(length=80), nullable=False))
    op.alter_column('vehicles', 'model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('vehicles', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vehicles', 'plate',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False)
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint('vehicles_owner_user_id_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vehicles', 'owner_user_id')
    op.drop_column('vehicles', 'make')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_owner_user_id_fkey', 'vehicles', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('vehicles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('vehicles', 'plate',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('vehicles', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vehicles', 'model',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('vehicles', 'brand')
    op.drop_column('vehicles', 'store_id')
    # ### end Alembic commands ###
