"""Add owner_id to stores table

Revision ID: 1da9027b168b
Revises: b3cc4e24dfba
Create Date: 2025-09-30 15:14:47.335079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da9027b168b'
down_revision: Union[str, None] = 'b3cc4e24dfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint('stores_owner_user_id_fkey', 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stores', 'owner_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key('stores_owner_user_id_fkey', 'stores', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stores', 'owner_id')
    # ### end Alembic commands ###
