"""Add advertisement, plan and transaction tables

Revision ID: 9cbff77c8455
Revises: 1da9027b168b
Create Date: 2025-09-30 23:29:55.812130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbff77c8455'
down_revision: Union[str, None] = '1da9027b168b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
