"""Add advertisement, plan and transaction tables

Revision ID: eea1efd16f49
Revises: 9cbff77c8455
Create Date: 2025-09-30 23:35:58.259844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea1efd16f49'
down_revision: Union[str, None] = '9cbff77c8455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
