
services:
  test_runner:
    build:
      context: .
      dockerfile: Docker/fastapi.Dockerfile
      target: test  
    container_name: test_runner
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres_db:5432/brasiltransporta
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: >
      bash -c "
        set -e
        echo '🔄 Executando migrations...'
        alembic upgrade head
        echo '🧪 Executando testes...'
        pytest -v --disable-warnings --tb=short --durations=10 --maxfail=5
      "