# docker-compose.yml (Compose V2)
name: brasiltransporta

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-brasiltransporta}
    ports:
      - "5432:5432"
    volumes:
      - brasiltransporta_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-brasiltransporta}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI

  fastapi_app:
    build:
      context: .
      dockerfile: Docker/fastapi.Dockerfile     # <— padronizado
      target: runtime
    container_name: fastapi_app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@postgres_db:5432/brasiltransporta}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672//}
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    entrypoint: ["/app/Docker/entrypoint.sh"]   # <— ajuste o caminho/case
    command: uvicorn brasiltransporta.presentation.api.app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  tests:
    build:
      context: .
      dockerfile: Docker/fastapi.Dockerfile     # <— padronizado
      target: test
    container_name: brasiltransporta_tests
    volumes:
      - ./:/app:delegated
    environment:
      # se seus testes usarem o Postgres/Redis, mantenha estas URLs;
      # se usarem SQLite nos fixtures, isso nem será lido
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@postgres_db:5432/brasiltransporta}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672//}
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    command: ["pytest", "-q"]

volumes:
  brasiltransporta_pgdata:
