services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brasiltransporta
    ports:
      - "5432:5432"
    volumes:
      - brasiltransporta_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  fastapi_app:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    container_name: fastapi_app
    command: uvicorn brasiltransporta.presentation.api.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8001:8000"   # host:container (use 8001 no host para evitar conflito)
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres_db:5432/brasiltransporta
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - postgres_db
      - redis
      - rabbitmq

volumes:
  brasiltransporta_pgdata:
