from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.advertisement import Advertisement

class AdvertisementRepository(Protocol):
    def add(self, advertisement: Advertisement) -> None: ...
    def get_by_id(self, advertisement_id: str) -> Optional[Advertisement]: ...
    def list_by_store(self, store_id: str, limit: int = 50) -> List[Advertisement]: ...
    def list_active(self, region: Optional[str] = None, limit: int = 50) -> List[Advertisement]: ...
    def list_featured(self, limit: int = 20) -> List[Advertisement]: ...
    def update(self, advertisement: Advertisement) -> None: ...
