# 📄 brasiltransporta/domain/repositories/phone_verification_repository.py
from typing import Protocol, Optional
from brasiltransporta.domain.entities.phone_verification import PhoneVerification

class PhoneVerificationRepository(Protocol):
    def save(self, verification: PhoneVerification) -> PhoneVerification: ...
    def get_by_phone(self, phone: str) -> Optional[PhoneVerification]: ...
    def delete(self, verification_id: str) -> bool: ...
    def delete_by_phone(self, phone: str) -> bool: ...