from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.plan import Plan

class PlanRepository(Protocol):
    def add(self, plan: Plan) -> None: ...
    def get_by_id(self, plan_id: str) -> Optional[Plan]: ...
    def list_all(self, limit: int = 50) -> List[Plan]: ...
