from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.store import Store

class StoreRepository(Protocol):
    def add(self, store: Store) -> None: ...
    def get_by_id(self, store_id: str) -> Optional[Store]: ...
    def list_by_owner(self, owner_id: str) -> List[Store]: ...
    def list_all(self, limit: int = 100) -> List[Store]: ...