from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.transaction import Transaction

class TransactionRepository(Protocol):
    def add(self, transaction: Transaction) -> None: ...
    def get_by_id(self, transaction_id: str) -> Optional[Transaction]: ...
    def list_by_user(self, user_id: str, limit: int = 50) -> List[Transaction]: ...
    def list_all(self, limit: int = 100) -> List[Transaction]: ...
