from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.transaction import Transaction, TransactionStatus

class TransactionRepository(Protocol):
    def add(self, transaction: Transaction) -> None: ...
    def get_by_id(self, transaction_id: str) -> Optional[Transaction]: ...
    def get_by_external_id(self, external_id: str) -> Optional[Transaction]: ...
    def list_by_user(self, user_id: str, limit: int = 50) -> List[Transaction]: ...
    def list_by_status(self, status: TransactionStatus, limit: int = 50) -> List[Transaction]: ...
    def update(self, transaction: Transaction) -> None: ...
