from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.user import User

class UserRepository(Protocol):
    def add(self, user: User) -> None: ...
    def get_by_id(self, user_id: str) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def list_by_region(self, region: str, limit: int = 50) -> List[User]: ...
    def find_by_phone(self, phone: str) -> Optional[User]:...