from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.vehicle import Vehicle

class VehicleRepository(Protocol):
    def add(self, vehicle: Vehicle) -> None: ...
    def get_by_id(self, vehicle_id: str) -> Optional[Vehicle]: ...
    def list_by_owner(self, owner_id: str) -> List[Vehicle]: ...
    def list_all(self, limit: int = 100) -> List[Vehicle]: ...