# domain/repositories/plan_repository.py
from typing import Protocol, Optional, List
from brasiltransporta.domain.entities.plan import Plan, PlanType, BillingCycle

class PlanRepository(Protocol):
    def add(self, plan: Plan) -> None: ...
    def get_by_id(self, plan_id: str) -> Optional[Plan]: ...
    def get_by_type_and_cycle(self, plan_type: PlanType, billing_cycle: BillingCycle) -> Optional[Plan]: ...
    def list_active(self) -> List[Plan]: ...
    def update(self, plan: Plan) -> None: ...
