[tool.poetry]
name = "brasiltransporta"
version = "0.1.0"
description = "Projeto Brasiltransporta usando Poetry + Docker"
authors = ["Antonio Junior <seu-email@exemplo.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
uvicorn = "^0.23.0"

[tool.poetry.dev-dependencies]
