name: CI

on:
  push:
    branches: [ main, chore/**, feat/**, fix/**, ci/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U app -d app"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://app:app@localhost:5432/app
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Install project (editable)
        run: pip install -e .

      - name: Sanity import
        run: |
          python - << 'PY'
          import importlib, sys
          print("sys.path[0]:", sys.path[0])
          m = importlib.import_module("brasiltransporta")
          print("brasiltransporta module:", getattr(m, "__file__", "(namespace package)"))
          PY

      - name: (Optional) Alembic migrations
        run: |
          if command -v alembic >/dev/null 2>&1; then
            alembic -c alembic.ini upgrade head || true
          fi

      - name: Pytest
        run: pytest -q
