name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite trigger manual

jobs:
  deploy:
    runs-on: ubuntu-latest   # ✅ Alterado para Linux para compatibilidade Docker
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          echo "✅ Docker já está disponível no runner Ubuntu"

      - name: Deploy with PowerShell
        shell: pwsh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          Write-Host "🚀 Iniciando deploy..."
          
          # Verificar branch
          Write-Host "📋 Branch: $env:GITHUB_REF"
          
          # Construir e subir containers Docker
          Write-Host "📦 Construindo imagens e subindo containers..."
          docker compose up -d --build
          
          # Se usar push para Docker Hub:
          # docker build -t $env:DOCKERHUB_USERNAME/brasiltransporta-fastapi -f docker/fastapi.Dockerfile .
          # docker push $env:DOCKERHUB_USERNAME/brasiltransporta-fastapi
          
          Write-Host "✅ Deploy completado com sucesso!"
          Write-Host "🌐 Aplicação disponível em: https://brasiltransporta.com"
