name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite trigger manual

jobs:
  deploy:
    runs-on: ubuntu-latest   # ✅ Alterado para Linux para compatibilidade Docker
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          echo "✅ Docker já está disponível no runner Ubuntu"

      - name: Deploy with Docker Compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "🚀 Iniciando deploy..."
          echo "📋 Branch: $GITHUB_REF"
          
          # Construir e subir containers Docker
          echo "📦 Construindo imagens e subindo containers..."
          docker compose up -d --build
          
          echo "✅ Deploy completado com sucesso!"
          echo "🌐 Aplicação disponível em: https://brasiltransporta.com"
