name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          echo "✅ Docker já está disponível no runner Ubuntu"

      - name: Deploy with Docker Compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "🚀 Iniciando deploy..."
          echo "📋 Branch: $GITHUB_REF"

          # Verificar versões do Docker
          docker --version
          docker compose version

          # Construir e subir containers Docker (COMANDO CORRETO)
          echo "📦 Construindo containers e subindo..."
          docker compose up -d --build

          echo "✅ Deploy completado com sucesso!"
          echo "🌐 Aplicação disponível em: https://brasiltransporta.com"